

seed: 870

dataset:
  name: SkinDataset
  meta: true
  params:
    flip: true
    verbose: true
    square: true
    square_tta: 1
  inner_fold: 0
  outer_fold: 0
  outer_only: true
  data_dir: [../data/isic2019/ISIC_2019_Training_Input, ../data/train-640]
  csv_filename: ../data/combined_train_cdeotte_meta.csv


transform:
  augment: RandAugment
  params:
    n: 3
    m: 12.0
  num_workers: 0
  pad_ratio: null
  resize_to: [640, 640]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model:
  name: NetMeta2D
  params:
    backbone: null
    pretrained: true
    num_classes: 2
    dropout: 0.2
    multisample_dropout: true


find_lr: # this is its own mode 
  params:
    start_lr: 1.0e-7
    end_lr: 1
    num_iter: 500
    save_fig: true


train:
  batch_size: 64
  trainer: Trainer
  params:
    gradient_accumulation: 1
    num_epochs: 9
    steps_per_epoch: 0
    validate_interval: 3
    verbosity: 100
    amp: true


evaluation:
  batch_size: 1
  evaluator: Evaluator
  params:
    save_checkpoint_dir: ../checkpoints/bee020/
    save_best: true
    prefix: effnet
    metrics: [auc2]
    valid_metric: auc2
    mode: max
    improve_thresh: 1.0e-6


loss:
  name: CrossEntropyLoss
  params:


optimizer:
  name: AdamW
  params:
    lr: 3.0e-4
    weight_decay: 5.0e-4


scheduler:
  name: CosineAnnealingWarmRestarts
  params:
    final_lr: 1.0e-8
    num_snapshots: 3


test:
  checkpoint: ../checkpoints/skp007/EFFB4_000_VM-0.9312.PTH
  predictor: Predictor
  savefile: ../cv-predictions/fold0/skp007.pkl
  params:
