# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 88 

dataset:
  name: SkinDataset
  params:
    flip: false
    verbose: true
    square: true
    square_tta: 10
  data_dir: ../data/train-512/


transform:
  augment: null
  params:
  num_workers: 0
  pad_ratio: null
  resize_to: [512, 512]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model_configs:
  - configs/isic2019/mk001.yaml


model_checkpoints:
  - ../checkpoints/isic2019/mk001/EFFNET_039_VM-0.9644.PTH


predict:
  predictor: Predictor
  savefile: ../train-predictions/isic2019-mk001.pkl 
