# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 88 

dataset:
  name: SkinDataset
  params:
    flip: false
    verbose: true
  data_dir: ../data/jpeg/test/
  arc_csvfile: ../data/train_with_stratified_splits.csv
  arc_datadir: ../data/jpeg/train/


transform:
  augment: null
  params:
  num_workers: 0
  pad_ratio: 0.666667
  resize_to: [480, 720]
  crop_size: [420, 630]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]



model_configs:
  - configs/skp/skp008.yaml


model_checkpoints:
  - ../checkpoints/skp008/EFFB4_000_VM-0.9163.PTH


arc: true


predict:
  predictor: Predictor
  savefile: ../cv-predictions/skp008.pkl 
