# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 88 

dataset:
  name: SkinDataset
  meta: true
  params:
    flip: false
    verbose: true
    square: true
    square_tta: 10
  data_dir: ../data/jpeg/test/
  csv_filename: ../data/test_with_meta.csv


transform:
  augment: vanilla_transform
  params:
    p: 0.8
  num_workers: 0
  pad_ratio: null
  resize_to: [512, 512]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model_configs:
  - configs/skp/skp024.yaml
  - configs/skp/skp024.yaml
  - configs/skp/skp024.yaml
  - configs/skp/skp024.yaml
  - configs/skp/skp024.yaml


model_checkpoints:
  - ../checkpoints/skp024/fold0/EFFB4_000_VM-0.9407.PTH
  - ../checkpoints/skp024/fold1/EFFB4_000_VM-0.9290.PTH
  - ../checkpoints/skp024/fold2/EFFB4_000_VM-0.9414.PTH
  - ../checkpoints/skp024/fold3/EFFB4_000_VM-0.9285.PTH
  - ../checkpoints/skp024/fold4/EFFB4_000_VM-0.9286.PTH


predict:
  predictor: Predictor
  savefile: ../lb-predictions/skp024-5fold.pkl 
