# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 88 

dataset:
  name: SkinDataset
  params:
    flip: false
    verbose: true
  data_dir: ../data/cropped/test/


transform:
  augment: vanilla_transform
  params:
    p: 0.8
  num_workers: 0
  pad_ratio: 1.0
  resize_to: [512, 512]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model_configs:
  - configs/skp/skp009.yaml
  - configs/skp/skp009.yaml
  - configs/skp/skp009.yaml
  - configs/skp/skp009.yaml
  - configs/skp/skp009.yaml


model_checkpoints:
  - ../checkpoints/skp009/EFFB4_000_VM-0.9246.PTH
  - ../checkpoints/skp009/fold1/EFFB4_000_VM-0.9281.PTH
  - ../checkpoints/skp009/fold2/EFFB4_000_VM-0.9246.PTH
  - ../checkpoints/skp009/fold3/EFFB4_000_VM-0.9280.PTH
  - ../checkpoints/skp009/fold4/EFFB4_000_VM-0.9179.PTH


predict:
  predictor: Predictor
  savefile: ../lb-predictions/skp009-5fold.pkl 
