seed: 88 

dataset:
  name: SkinDataset
  params:
    flip: true
    verbose: true
    square: true
    square_tta: 3
  inner_fold: 0
  outer_fold: 0
  outer_only: true
  data_dir: ..
  csv_filename: ../data/train_adv_2019_2020.csv


transform:
  augment: vanilla_transform
  params:
    p: 0.8
  num_workers: 0
  pad_ratio: null
  resize_to: [512, 512]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model:
  name: Net2D
  params:
    backbone: tf_efficientnet_b4
    pretrained: true
    num_classes: 2
    dropout: 0.2
    multisample_dropout: true


find_lr: # this is its own mode 
  params:
    start_lr: 1.0e-7
    end_lr: 1
    num_iter: 500
    save_fig: true


train:
  batch_size: 16
  trainer: Trainer
  params:
    gradient_accumulation: 1
    num_epochs: 10
    steps_per_epoch: 0
    validate_interval: 2
    verbosity: 100
    amp: true


evaluation:
  batch_size: 1
  evaluator: Evaluator
  params:
    save_checkpoint_dir: ../checkpoints/adv000/
    save_best: true
    prefix: effb4
    metrics: [auc2]
    valid_metric: auc2
    mode: max
    improve_thresh: 1.0e-6


loss:
  name: CrossEntropyLoss
  params:


optimizer:
  name: AdamW
  params:
    lr: 1.2e-5
    weight_decay: 5.0e-4


scheduler:
  name: CustomOneCycleLR
  params:
    max_lr:   3.0e-4
    final_lr: 1.0e-12
    pct_start: 0.3


test:
  checkpoint: ../checkpoints/skp007/EFFB4_000_VM-0.9312.PTH
  predictor: Predictor
  savefile: ../cv-predictions/fold0/skp007.pkl
  params:
